openapi: 3.0.1
info:
  title: Travel Plugin
  description: A plugin that allows the user to find the Position of Interests while using ChatGPT.
  version: 'v1'
servers:
  - url: https://nextjs-chatgpt-plugin-starter.vercel.app
paths:
  /api/get-poi:
    post:
      operationId: getPois
      summary: Get the list of position of interest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/searchPoiRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPoiResponse'
  /api/todos:
    get:
      operationId: getTodos
      summary: Get the list of todos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTodosResponse'
  /api/create-todo:
    post:
      operationId: addTodo
      summary: add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addTodoRequest'
      responses:
        "200":
          description: OK
  /api/delete-todo:
    post:
      operationId: deleteTodo
      summary: delete a todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteTodoRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    deleteTodoRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to delete from the list.
          required: true
    addTodoRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to add to the list.
          required: true
    searchPoiRequest:
      type: object
      required:
      - keyword
      properties:
        keyword:
          type: string
          description: The keyword for searching the position of interest.
          required: true
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.
    getPoiResponse:
      type: object
      required:
      - keyword
      properties:
        pois:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/poiInfo'
          description: The list of Position of Interest.
    poiInfo:
      type: object
      properties:
        poiId:
          type: string
          description: Unique Id of LINE travel.
        poiURL:
          type: string
          description: The link to POI detail information.
        name:
          type: string
          description: Name of the POI.
        nameEn:
          type: string
          description: English name of the POI.
        nickname:
          type: array
          items:
            type: string
          description: The nicknames of the POI.
        latitude:
          type: number
          description: Latitude of the POI.
        longitude:
          type: number
          description: Longitude of the POI.
        score:
          type: number
          description: Matching score.
        coverPhoto:
          type: string
          description: The image url of cover photo of the POI.
